lunion-play: Implement dxvk & vkd3d-proton integration

diff --git a/lunion-play b/lunion-play
--- a/lunion-play
+++ b/lunion-play
@@ -110,6 +110,75 @@ display_runtime_options()
   fi
 }
 
+override_dll() {
+  wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v $1 /d native /f >/dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    error "Failed to add override for $1"
+    exit 1
+  fi
+}
+
+install_dll() {
+  dstfile="${1}/${3}.dll"
+  srcfile="${2}/${3}.dll"
+
+  if ! [ -f "${srcfile}" ]; then
+    warn "${srcfile}: File not found. Skipping." >&2
+    return 1
+  fi
+
+  if [ -n "$1" ]; then
+    if [ -f "${dstfile}" ] || [ -h "${dstfile}" ]; then
+      if ! [ -f "${dstfile}.old" ]; then
+        mv "${dstfile}" "${dstfile}.old"
+      else
+        rm "${dstfile}"
+      fi
+    else
+      touch "${dstfile}.old_none"
+    fi
+    ln -s "${srcfile}" "${dstfile}"
+  fi
+  return 0
+}
+
+install_dxvk()
+{
+  for dll in dxgi d3d9 d3d10core d3d11; do
+    for arch in x64 x32; do
+      case "$arch" in
+      "x64")
+        path="$WINEPREFIX"/drive_c/windows/system32
+        ;;
+      "x32")
+        path="$WINEPREFIX"/drive_c/windows/syswow64
+        ;;
+      esac
+
+      install_dll "$path" "$1/$arch" "$dll"
+      override_dll "$dll"
+    done
+  done
+}
+
+install_vkd3dproton()
+{
+  for arch in x64 x86; do
+    case "$arch" in
+    "x64")
+      path="$WINEPREFIX"/drive_c/windows/system32
+      ;;
+    "x32")
+      path="$WINEPREFIX"/drive_c/windows/syswow64
+      ;;
+    esac
+
+    install_dll "$path" "$1/$arch" d3d12
+    override_dll d3d12
+  done
+}
+
+
 
 # ========================================
 #  Lunion Play configuration Verification
@@ -305,6 +374,16 @@ fi
 #  DXVK Configuration
 # ====================
 
+# Verify dxvk folder is present
+system_dxvk="/usr/share/lunion-play/dxvk"
+local_dxvk="$where/dxvk"
+
+if [[ "$where" =~ ^/+usr/+bin/*.* ]] && [ -d "$system_dxvk/x64" ] && [ -d "$system_dxvk/x64" ] && [ -f "$system_dxvk/setup_dxvk.sh" ]; then
+  install_dxvk "$system_dxvk"
+elif [[ "$where" != ^/+usr/+bin/*.* ]] && [ -d "$loc_dxvk/x64" ] && [ -d "$local_dxvk/x32" ] && [ -f "$local_dxvk/setup_dxvk.sh" ]; then
+  install_dxvk "$local_dxvk"
+fi
+
 mkdir -p "$GAME_DIR"/shaderscache/dxvk_state_cache
 export DXVK_STATE_CACHE_PATH="$GAME_DIR"/shaderscache/dxvk_state_cache
 
@@ -318,6 +397,16 @@ fi
 # ============================
 #  VKD3D-Proton Configuration
 # ============================
+
+# Verify vkd3d-proton folder is present
+system_vkd3dproton="/usr/share/lunion-play/vkd3d-proton"
+local_vkd3dproton="$where/vkd3d-proton"
+
+if [[ "$where" =~ ^/+usr/+bin/*.* ]] && [ -d "$sys_vkd3dproton"/x64 ] && [ -d "$sys_vkd3dproton"/x64 ] && [ -f "$sys_vkd3dproton"/setup_vkd3dproton.sh ]; then
+  install_vkd3dproton "$sys_vkd3dproton"
+elif [[ "$where" != ^/+usr/+bin/*.* ]] && [ -d "$local_vkd3dproton/x64" ] && [ -d "$local_vkd3dproton/x32" ] && [ -f "$local_vkd3dproton/setup_vkd3dproton.sh" ]; then
+  install_vkd3dproton "$local_vkd3dproton"
+fi
 
 if [[ "$LUNION_PLAY_LOG" -gt 0 ]] && [ -z "$VKD3D_DEBUG" ]; then
   export VKD3D_DEBUG=warn
