[lunion-gamesetup] Fix colors

diff --git a/lunion-gamesetup b/lunion-gamesetup
--- a/lunion-gamesetup
+++ b/lunion-gamesetup
@@ -19,22 +19,22 @@ fi
 
 msg()
 {
-  echo -e "  \033[1;34m->\033[1;0m \033[1;1m$1\033[1;0m" >&2
+  echo -e "  \033[1;34m->\033[1;0m\033[1;1m $1\033[1;0m" >&2
 }
 
 dialog()
 {
-  echo -en "\033[1;34m::\033[1;0m \033[1;1m$1\033[1;0m" >&2
+  echo -en "\033[1;34m::\033[1;0m\033[1;1m $1\033[1;0m" >&2
 }
 
 warning()
 {
-  echo -e "\033[1;31m==> WARNING: $1\033[1;0m" >&2
+  echo -e "\033[1;33m==> WARNING:\033[1;0m\033[1;1m $1\033[1;0m" >&2
 }
 
 error()
 {
-  echo -e "\033[1;31m==> ERROR:\033[1;0m \033[1;1m$1\033[1;0m" >&2
+  echo -e "\033[1;31m==> ERROR:\033[1;0m\033[1;1m $1\033[1;0m" >&2
 }
 
 winewait()
